name: C++ Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenCV
        run: sudo apt-get install -y libopencv-dev
      - name: Configure with CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build
