name: C++ Build

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3

  - name: Install OpenCV
    run: |
      sudo apt-get update
      sudo apt-get install -y --fix-missing libopencv-dev ninja-build

  - name: Configure with CMake
    run: cmake -B build -G Ninja

  - name: Build
    run: cmake --build build
